import { useState, useCallback, useRef, useEffect } from 'react'
import type { TableDto } from '../../api/types'
import './FloorPlan.css'

/**
 * stub elements were initially generated by AI and then manually adjusted.
 * they are also used as a fallback when the API is not connected.
 */

interface StubTable {
  id: string
  capacity: number
  zoneId: string
  x: number
  y: number
  width: number
  height: number
  state?: 'available' | 'occupied' | 'recommended'
}

interface FloorPlanProps {
  tables?: TableDto[]
  showRecommendations?: boolean
  isAdminMode?: boolean
  onTableClick?: (tableId: string, capacity?: number) => void
  onTablePositionChange?: (tableId: string, x: number, y: number, zoneId: string) => void
}

// static layout. available/occupied/recommended demo.
const STUB_TABLES: StubTable[] = [
  { id: 'T1', capacity: 4, zoneId: 'main', x: 45, y: 150, width: 50, height: 40, state: 'available' },
  { id: 'T2', capacity: 2, zoneId: 'private', x: 400, y: 42, width: 45, height: 35, state: 'available' },
  { id: 'T3', capacity: 6, zoneId: 'terrace', x: 45, y: 255, width: 55, height: 42, state: 'available' },
  { id: 'T4', capacity: 6, zoneId: 'terrace', x: 220, y: 255, width: 55, height: 42, state: 'available' },
  { id: 'T5', capacity: 6, zoneId: 'terrace', x: 330, y: 255, width: 55, height: 42, state: 'available' },
  { id: 'T7', capacity: 4, zoneId: 'main', x: 235, y: 150, width: 50, height: 40, state: 'available' },
  { id: 'T8', capacity: 4, zoneId: 'main', x: 235, y: 50, width: 50, height: 40, state: 'available' },
]

//zone rectangles and display names for tooltips
const ZONES = [
  { id: 'main', name: 'Indoors', x: 20, y: 20, width: 320, height: 190 },
  { id: 'private', name: 'Private room', x: 340, y: 20, width: 140, height: 80 },
  { id: 'terrace', name: 'Terrace', x: 20, y: 210, width: 412, height: 120 },
  { id: 'kitchen', name: 'Kitchen', x: 340, y: 101, width: 170, height: 110 }
] as const

//wall segments
const WALLS = [
  { x: 19, y: 19, w: 320, h: 2 }, // indoors top wall
  { x: 19, y: 19, w: 2, h: 50 }, // indoors left top wall
  { x: 19, y: 109, w: 2, h: 190 }, // indoors left bottom wall
  { x: 339, y: 180, w: 2, h: 30 }, // indoor kitchen bottom wall
  { x: 339, y: 101, w: 2, h: 30 }, // indoor kirchen top wall
  { x: 339, y: 209, w: 170, h: 2 }, // kitchen bottom wall
  { x: 339, y: 19, w: 2, h: 20 }, // indoors private room top wall
  { x: 339, y: 79, w: 2, h: 20 }, // indoors private room bottom wall
  { x: 339, y: 19, w: 142, h: 2 }, // private room top wall
  { x: 481, y: 19, w: 2, h: 82 }, // private room right wall
  { x: 339, y: 99, w: 170, h: 2 }, // private room bottom wall
  { x: 179, y: 209, w: 250, h: 2 }, // terrace top right wall
  { x: 19, y: 209, w: 100, h: 2 }, // terrace top left wall
  { x: 19, y: 209, w: 2, h: 122 }, // terrace left wall
  { x: 429, y: 209, w: 2, h: 122 }, // terrace right wall
  { x: 19, y: 329, w: 412, h: 2 }, // terrace bottom wall
]

const VIEWBOX = { width: 500, height: 350 }

/** returns zone id containing point */
function getZoneAt(x: number, y: number): string | null {
  for (const z of ZONES) {
    if (x >= z.x && x < z.x + z.width && y >= z.y && y < z.y + z.height) return z.id
  }
  return null
}

export default function FloorPlan(props: FloorPlanProps) {
  const { tables = [], showRecommendations = false, isAdminMode = false, onTableClick, onTablePositionChange } = props
  const svgRef = useRef<SVGSVGElement>(null)
  const justDraggedRef = useRef<string | null>(null)
  const onTablePositionChangeRef = useRef(onTablePositionChange)
  onTablePositionChangeRef.current = onTablePositionChange
  const useApiTables = tables.length > 0 && tables.every((t) => 'occupied' in t && 'width' in t)
  const displayTables: Array<StubTable & { occupied?: boolean; recommended?: boolean }> = useApiTables
    ? (tables as TableDto[]).map((t) => ({
        id: t.id,
        capacity: t.capacity,
        zoneId: t.zoneId,
        x: t.x,
        y: t.y,
        width: t.width,
        height: t.height,
        state: t.occupied ? 'occupied' : t.recommended ? 'recommended' : 'available',
        occupied: t.occupied,
        recommended: t.recommended,
      }))
    : STUB_TABLES
  const [tooltip, setTooltip] = useState<{ text: string; x: number; y: number } | null>(null)
  const [dragState, setDragState] = useState<{
    tableId: string
    x: number
    y: number
    offsetX: number
    offsetY: number
    hasMoved: boolean
    width: number
    height: number
    zoneId: string
  } | null>(null)

  const clientToSvg = useCallback((clientX: number, clientY: number) => {
    const svg = svgRef.current
    if (!svg) return { x: 0, y: 0 }
    const pt = svg.createSVGPoint()
    pt.x = clientX
    pt.y = clientY
    const t = pt.matrixTransform(svg.getScreenCTM()?.inverse())
    return { x: t.x, y: t.y }
  }, [])

  useEffect(() => {
    if (!dragState) return
    const onMove = (e: MouseEvent) => {
      const { x, y } = clientToSvg(e.clientX, e.clientY)
      setDragState((prev) =>
        prev
          ? {
              ...prev,
              x: Math.max(0, x - prev.offsetX),
              y: Math.max(0, y - prev.offsetY),
              hasMoved: true,
            }
          : null
      )
    }
    const onUp = () => {
      setDragState((prev) => {
        if (!prev) return null
        if (prev.hasMoved) {
          justDraggedRef.current = prev.tableId
          const centerX = prev.x + prev.width / 2
          const centerY = prev.y + prev.height / 2
          const zoneId = getZoneAt(centerX, centerY) ?? prev.zoneId
          const tableId = prev.tableId
          const x = prev.x
          const y = prev.y
          // invoke callback after this render to avoid "setState during render" of parent
          const cb = onTablePositionChangeRef.current
          if (cb) {
            queueMicrotask(() => {
              cb(tableId, x, y, zoneId)
            })
          }
          setTimeout(() => {
            justDraggedRef.current = null
          }, 0)
        }
        return null
      })
    }
    window.addEventListener('mousemove', onMove)
    window.addEventListener('mouseup', onUp)
    return () => {
      window.removeEventListener('mousemove', onMove)
      window.removeEventListener('mouseup', onUp)
    }
  }, [dragState, clientToSvg])

  const handleTableClick = (tableId: string, capacity?: number) => {
    if (justDraggedRef.current === tableId) return
    onTableClick?.(tableId, capacity)
  }

  const handleTableMouseDown = useCallback(
    (e: React.MouseEvent, t: StubTable & { occupied?: boolean }) => {
      if (!isAdminMode || !onTablePositionChange) return
      e.preventDefault()
      const { x, y } = clientToSvg(e.clientX, e.clientY)
      setDragState({
        tableId: t.id,
        x: t.x,
        y: t.y,
        offsetX: x - t.x,
        offsetY: y - t.y,
        hasMoved: false,
        width: t.width,
        height: t.height,
        zoneId: t.zoneId,
      })
    },
    [isAdminMode, onTablePositionChange, clientToSvg]
  )

  const handlePointerMove = useCallback((e: React.MouseEvent) => {
    setTooltip((prev) => (prev ? { ...prev, x: e.clientX, y: e.clientY } : null))
  }, [])

  return (
    <div
      className="floor-plan"
      data-show-recommendations={showRecommendations}
      onMouseMove={handlePointerMove}
      onMouseLeave={() => setTooltip(null)}
    >
      <svg
        ref={svgRef}
        className="floor-plan__svg"
        viewBox={`0 0 ${VIEWBOX.width} ${VIEWBOX.height}`}
        preserveAspectRatio="xMidYMid meet"
        aria-label="Restaurant floor plan"
      >
        {ZONES.map((z) => (
          <rect
            key={z.id}
            className={`floor-plan__zone floor-plan__zone--${z.id}`}
            x={z.x}
            y={z.y}
            width={z.width}
            height={z.height}
            aria-hidden
            onMouseEnter={(e) => setTooltip({ text: z.name, x: e.clientX, y: e.clientY })}
            onMouseLeave={() => setTooltip(null)}
          />
        ))}
        {/* walls */}
        {WALLS.map((w, i) => (
          <rect
            key={`wall-${i}`}
            className="floor-plan__wall"
            x={w.x}
            y={w.y}
            width={w.w}
            height={w.h}
            aria-hidden
          />
        ))}
        {displayTables.map((t) => {
          const isDragging = dragState?.tableId === t.id
          const rx = isDragging ? dragState!.x : t.x
          const ry = isDragging ? dragState!.y : t.y
          const stateClass = (t as StubTable).state ? `floor-plan__table--${(t as StubTable).state}` : ''
          const cx = rx + t.width / 2
          const cy = ry + t.height / 2
          const starSize = Math.min(t.width, t.height) * 0.35
          return (
            <g key={t.id}>
              <rect
                className={`floor-plan__table ${stateClass}${isAdminMode ? ' floor-plan__table--draggable' : ''}`}
                x={rx}
                y={ry}
                width={t.width}
                height={t.height}
                data-table-id={t.id}
                aria-label={`Table ${t.id}, ${t.capacity} seats${t.occupied ? ' (occupied)' : ''}${t.recommended ? ' (recommended)' : ''}`}
                onClick={() => {
                  if (t.occupied) return
                  handleTableClick(t.id, t.capacity)
                }}
                onMouseDown={isAdminMode ? (e) => handleTableMouseDown(e, t) : undefined}
                role="button"
                tabIndex={t.occupied ? -1 : 0}
                onMouseEnter={(e) =>
                  setTooltip({
                    text: `Table ${t.id} – ${t.capacity} seats${t.occupied ? ' (occupied)' : ''}${t.recommended ? ' ★ recommended' : ''}`,
                    x: e.clientX,
                    y: e.clientY,
                  })
                }
                onMouseLeave={() => setTooltip(null)}
                onKeyDown={(e) => {
                  if (t.occupied) return
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    handleTableClick(t.id, t.capacity)
                  }
                }}
              />
              {t.recommended && (
                <g
                  className="floor-plan__table-star"
                  transform={`translate(${cx}, ${cy}) scale(${starSize / 10})`}
                  pointerEvents="none"
                >
                  <path
                    fill="#c9a227"
                    stroke="#8b6914"
                    strokeWidth="0.6"
                    d="M0,-10 L2.94,-4.05 L9.51,-3.09 L5.05,1.55 L6.76,8.47 L0,4 L-6.76,8.47 L-5.05,1.55 L-9.51,-3.09 L-2.94,-4.05 Z"
                  />
                </g>
              )}
            </g>
          )
        })}
      </svg>
      {tooltip && (
        <div
          className="floor-plan__tooltip"
          style={{ left: tooltip.x, top: tooltip.y }}
          role="tooltip"
        >
          {tooltip.text}
        </div>
      )}
    </div>
  )
}
